library(ggplot2)
library(caret)
library(rpart)
library(rpart.plot)
library(RWeka)
library(RColorBrewer)
library(rattle)
library(Rgraphviz)
#4Ques1
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("Rgraphviz")
team<-read.csv("C:/Users/shrut/Documents/MachineLearning/HW3/train.csv")
gini<-rpart(Label~.,data=team,control=rpart.control(minsplit = 1,minbucket = 1,cp=0.01))
summary(gini)
rpart.plot(gini)
fancyRpartPlot(gini)
information<-rpart(Label~.,data=team,parms=list(split="information"),control=rpart.control(minsplit = 1,minbucket = 1,cp=0.01))
summary(information)
fancyRpartPlot(information)
gainratio<-J48(Label~.,data=team,control=Weka_control(M=1))
if(require("party", quietly = TRUE)) plot(gainratio)
print(gainratio)
summary(gainratio)
#4Ques2
weather<-read.csv("C:/Users/shrut/Documents/MachineLearning/HW3/Weather.csv")
weather_gini<-rpart(Label~.,data=weather,control=rpart.control(minsplit = 1,minbucket = 1,cp=0.01))
rpart.plot(weather_gini)
fancyRpartPlot(weather_gini)
weather_information<-rpart(Label~.,data=weather,parms=list(split="information"),control=rpart.control(minsplit = 1,minbucket = 1,cp=0.01))
fancyRpartPlot(weather_information)
summary(weather_gini)
summary(weather_information)
weather_gainratio<-J48(Label~.,data=weather,control=Weka_control(M=1))
ff <- tempfile()
write_to_dot(weather_gainratio, ff)
plot(agread(ff))
print(weather_gainratio)
#5Ques
football<-read.csv("C:/Users/shrut/Documents/MachineLearning/HW3/Football_train.csv")
football_gini<-rpart(Label~.,data=football,control=rpart.control(minsplit = 1,minbucket = 1,cp=0.01))
summary(football)
rpart.plot(football_gini)
fancyRpartPlot(football_gini)
football_information<-rpart(Label~.,data=football,parms=list(split="information"),control=rpart.control(minsplit = 1,minbucket = 1,cp=0.01))
summary(football_information)
rpart.plot(football_information)
fancyRpartPlot(football_information)
#football_gainratio<-J48(Label~.,data=football,control=Weka_control(M=1))
football_gainratio<-J48(Label~.,data=football,control=Weka_control(M=1,B=TRUE,U=TRUE))
#football_gainratio<-J48(Label~.,data=football,control=Weka_control(B=TRUE,U=TRUE))
ff <- tempfile()
write_to_dot(football_gainratio, ff)
plot(agread(ff))
print(football_gainratio)
summary(football_gainratio)
football_test<-read.csv("C:/Users/shrut/Documents/MachineLearning/HW3/Football_test.csv")
predictmodel1<-predict(football_information,football_test,type="class")
predictmodel1
predictmodel2<-predict(football_gainratio,football_test)
predictmodel2
table1<-table(predictmodel1,football_test$Label)
table2<-table(predictmodel2,football_test$Label)
testmodel1<-confusionMatrix(table1,positive = "Win")
testmodel1$byClass
testmodelwithgainratio<-confusionMatrix(table2,positive = "Win")
testmodelwithgainratio$byClass
precision(table1)